[default.extend-words]
profesor = "profesor"
PROFESOR = "PROFESOR"
Profesor = "Profesor"
momentos = "momentos"
historial = "historial"
presentes = "presentes"
informe = "informe"
clientes = "clientes"
productos = "productos"
problemas = "problemas"
momento = "momento"
constituye = "constituye"
